# **Python Pandas**

## Attribution

This notebook contains my learning achieved while following Keith Galli's Pandas tutorial.
The notebook closely follows the code demonstrated in the tutorial and was typed by me as part of the learning process. The accompanying datasets and the original tutorial materials are licensed under the MIT License by Keith Galli.

The original MIT License is included in this repository under the assets section.

# Table of Contents

1. Introduction to Pandas
2. Installing & Importing Pandas
3. Creating DataFrames
4. Understanding Rows, Columns & Index
5. Loading Data (CSV, Excel, Parquet, URL)
6. Exploring Data (head, tail, sample, info, describe)
7. DataFrame Properties (shape, size, columns, index, unique)
8. Selecting Rows & Columns (.loc, .iloc, .at, .iat)
9. Updating & Modifying Data
10. Sorting Data
11. Iterating Through DataFrames
12. Filtering Data
13. String-Based Filtering
14. Querying Data
15. Adding New Columns
16. Removing Columns & Rows
17. Renaming Columns
18. Copy vs Reference
19. String Operations (.str)
20. Working with Date & Time
21. Saving Data (CSV, Excel, Parquet)
22. Applying Functions (apply, lambda)
23. Merging DataFrames
24. Concatenating DataFrames
25. Handling Missing Values (NaN)
26. Aggregation & Value Counts
27. GroupBy Operations
28. Pivot Tables
29. Grouping with DateTime

In [ ]:
import pandas as pd

In [ ]:
#dataframe = table with all sort of extra functionalities
df = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]], columns=["A","B","C"])
df.head() #first 5 rows
df.head(1) #first row
df.head(2) #first 2 rows

df.tail(2) #last 2 rows

   A  B  C
1  4  5  6
2  7  8  9

In [ ]:
df.columns #to check the headers

Index(['A', 'B', 'C'], dtype='object')

In [ ]:
df.index.tolist() #index numbers converted to list

[0, 1, 2]

In [ ]:
df.info()  #to see information about our dataframe

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      int64
 1   B       3 non-null      int64
 2   C       3 non-null      int64
dtypes: int64(3)
memory usage: 204.0 bytes

In [ ]:
df.describe() #meaningful information about data

         A    B    C
count  3.0  3.0  3.0
mean   4.0  5.0  6.0
std    3.0  3.0  3.0
min    1.0  2.0  3.0
25%    2.5  3.5  4.5
50%    4.0  5.0  6.0
75%    5.5  6.5  7.5
max    7.0  8.0  9.0

In [ ]:
df.nunique() #number+unique values in each column

#df["A"].nunique()

A    3
B    3
C    3
dtype: int64

In [ ]:
df.shape #dimensions of the dataframe

(3, 3)

In [ ]:
df.size  #total elements

9

# **Loading in dataframes from files**

In [ ]:
coffee = pd.read_csv("coffee.csv")

In [ ]:
results = pd.read_parquet("results.parquet")
bios = pd.read_csv("bios.csv")

In [ ]:
results.head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,None,17.0,True,None
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,None
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,None,32.0,True,None
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,None
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,None

# **Accessing data with Pandas**

In [ ]:
display(coffee) #print(coffee), display(coffee)

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [ ]:
# to get random data from the file
coffee.sample(10)

          Day Coffee Type  Units Sold
12     Sunday    Espresso          45
11   Saturday       Latte          35
5   Wednesday       Latte          25
4   Wednesday    Espresso          35
7    Thursday       Latte          30
1      Monday       Latte          15
13     Sunday       Latte          35
3     Tuesday       Latte          20
10   Saturday    Espresso          45
6    Thursday    Espresso          40

In [ ]:
#to access specific values
# loc - to filter by rows and columns of df
coffee.loc[[0,5,9]] #to get rows of 0 5 9 idx
coffee.loc[5:9] # to get rows from range 5-9
coffee.loc[5:10,["Day", "Units Sold"]] # to get rows from 5-10 and columns only day and units sold

          Day  Units Sold
5   Wednesday          25
6    Thursday          40
7    Thursday          30
8      Friday          45
9      Friday          35
10   Saturday          45

In [ ]:
#iloc - works only with the indexes
coffee.iloc[:,[0,2]]

#almost the same -- notice with .iloc the upper index is not inclusive where with .loc it was inclusive

          Day  Units Sold
0      Monday          25
1      Monday          15
2     Tuesday          30
3     Tuesday          20
4   Wednesday          35
5   Wednesday          25
6    Thursday          40
7    Thursday          30
8      Friday          45
9      Friday          35
10   Saturday          45
11   Saturday          35
12     Sunday          45
13     Sunday          35

In [ ]:
# coffee.index = coffee.Day #or coffee["Day"]

In [ ]:
# # coffee.head()
# coffee.loc["Monday":"Wednesday", "Units Sold"]

In [ ]:
display(coffee)

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [ ]:
coffee.loc[1:3, "Units Sold"] = 10
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          10
2    Tuesday    Espresso          10
3    Tuesday       Latte          10
4  Wednesday    Espresso          35

In [ ]:
# to get specific values only .iat or .at
coffee.iat[0,1]

'Espresso'

In [ ]:
coffee.sort_values("Units Sold", ascending=False) #To sort values based on a column

          Day Coffee Type  Units Sold
10   Saturday    Espresso          45
8      Friday    Espresso          45
12     Sunday    Espresso          45
6    Thursday    Espresso          40
4   Wednesday    Espresso          35
11   Saturday       Latte          35
13     Sunday       Latte          35
9      Friday       Latte          35
7    Thursday       Latte          30
0      Monday    Espresso          25
5   Wednesday       Latte          25
2     Tuesday    Espresso          10
1      Monday       Latte          10
3     Tuesday       Latte          10

In [ ]:
coffee.sort_values(["Units Sold", "Coffee Type"], ascending = [0,1])

          Day Coffee Type  Units Sold
8      Friday    Espresso          45
10   Saturday    Espresso          45
12     Sunday    Espresso          45
6    Thursday    Espresso          40
4   Wednesday    Espresso          35
9      Friday       Latte          35
11   Saturday       Latte          35
13     Sunday       Latte          35
7    Thursday       Latte          30
0      Monday    Espresso          25
5   Wednesday       Latte          25
2     Tuesday    Espresso          10
1      Monday       Latte          10
3     Tuesday       Latte          10

# **Filtering Data**

In [ ]:
# bios.info()
bios.loc[bios["height_cm"] > 215 , ["name", "height_cm"]]

                         name  height_cm
5089       Viktor Pankrashkin      220.0
5583     Paulinho Villas Boas      217.0
5673           Gunther Behnke      221.0
5716                 Uwe Blab      218.0
5781           Tommy Burleson      223.0
5796            Andy Campbell      218.0
6223              Lars Hansen      216.0
6270              Hu Zhangbao      216.0
6409         Sergey Kovalenko      216.0
6420            Jānis Krūmiņš      218.0
6504              Luc Longley      220.0
6722         Shaquille O'Neal      216.0
6937           David Robinson      216.0
6978          Arvydas Sabonis      223.0
7074           Paulo da Silva      217.0
7188       Vladimir Tkachenko      220.0
7281         Stojko Vranković      217.0
7376      Eurelijus Žukauskas      218.0
52608         Aleksey Kazakov      217.0
82100           Frédéric Weis      218.0
89070                Yao Ming      226.0
89075          Roberto Dueñas      221.0
107408       Peter John Ramos      219.0
112312           Stanko Barać      217.0
112332    Andreas Glyniadakis      216.0
112337          Hamed Haddadi      218.0
118663         Timofey Mozgov      216.0
118676        Dmitry Musersky      219.0
120266           Zhang Zhaoxu      221.0
121694            Salah Mejri      216.0
123850         Tyson Chandler      216.0
130460               Li Muhao      218.0
130461                Zhou Qi      217.0
138671          Ondřej Balvín      216.0
139365         Moustapha Fall      218.0

In [ ]:
bios.loc[(bios["height_cm"] > 215) & (bios["born_country"] == "USA")]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
5781,5804,Tommy Burleson,1952-02-24,Crossnore,North Carolina,USA,United States,223.0,102.0,NaN
6722,6755,Shaquille O'Neal,1972-03-06,Newark,New Jersey,USA,United States,216.0,137.0,NaN
6937,6972,David Robinson,1965-08-06,Key West,Florida,USA,United States,216.0,107.0,NaN
123850,126093,Tyson Chandler,1982-10-02,Hanford,California,USA,United States,216.0,107.0,NaN

In [ ]:
bios[bios['name'].str.contains('Keith')]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
1897,1907,Keith Hanlon,1966-09-01,NaN,NaN,NaN,Ireland,NaN,NaN,NaN
3505,3517,Keith Wallace,1961-03-29,Preston,England,GBR,Great Britain,165.0,51.0,1999-12-31
6228,6255,Keith Hartley,1940-10-15,Vancouver,British Columbia,CAN,Canada,200.0,85.0,NaN
8898,8946,Keith Mwila,1966-01-01,NaN,NaN,NaN,Zambia,NaN,NaN,1993-01-09
12053,12118,Keith Hervey,1898-11-03,Fulham,England,GBR,Great Britain,NaN,NaN,1973-02-22
...,...,...,...,...,...,...,...,...,...,...
109900,111105,Keith Cumberpatch,1927-08-25,Christchurch,Canterbury,NZL,New Zealand,NaN,NaN,2013-11-15
115973,117348,Keith Sanderson,1975-02-02,Plymouth,Massachusetts,USA,United States,183.0,95.0,NaN
117676,119195,Duncan Keith,1983-07-16,Winnipeg,Manitoba,CAN,Canada,185.0,88.0,NaN
122121,124176,Keith Ferguson,1979-09-07,Sale,Victoria,AUS,Australia,176.0,78.0,NaN
127310,129749,Tracy Keith-Matchitt,1990-03-30,Palmerston North,Manawatu-Wanganui,NZL,Cook Islands,167.0,60.0,NaN

In [ ]:
bios[bios['born_country'].isin(['USA']) & (bios['name'].str.startswith('Keith'))]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
50929,51288,Keith Carter,1924-08-30,Akron,Ohio,USA,United States,NaN,NaN,2013-05-03
51185,51544,Keith Russell,1948-01-15,Mesa,Arizona,USA,United States,188.0,73.0,NaN
52913,53288,Keith Erickson,1944-04-19,San Francisco,California,USA,United States,196.0,86.0,NaN
62678,63144,Keith Notary,1960-01-22,Merritt Island,Florida,USA,United States,170.0,66.0,NaN
77550,78141,Keith Brantly,1962-05-23,Scott Air Force Base,Illinois,USA,United States,180.0,64.0,NaN
84097,84766,Keith Christiansen,1944-07-14,International Falls,Minnesota,USA,United States,165.0,69.0,2018-11-05
94646,95413,Keith Meyer,1938-06-20,Geneva,Illinois,USA,United States,NaN,NaN,2010-07-25
97499,98286,Keith Tkachuk,1972-03-28,Melrose,Massachusetts,USA,United States,188.0,102.0,NaN
98068,98860,Keith Wegeman,1929-08-28,Denver,Colorado,USA,United States,NaN,NaN,1974-08-22
99921,100722,Keith Carney,1970-02-03,Providence,Rhode Island,USA,United States,188.0,93.0,NaN
115973,117348,Keith Sanderson,1975-02-02,Plymouth,Massachusetts,USA,United States,183.0,95.0,NaN

timestamp 33:09

In [ ]:
bios.query("born_country == 'USA' and name.str.startswith('Keith')")
#To remove redundancy

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
50929,51288,Keith Carter,1924-08-30,Akron,Ohio,USA,United States,NaN,NaN,2013-05-03
51185,51544,Keith Russell,1948-01-15,Mesa,Arizona,USA,United States,188.0,73.0,NaN
52913,53288,Keith Erickson,1944-04-19,San Francisco,California,USA,United States,196.0,86.0,NaN
62678,63144,Keith Notary,1960-01-22,Merritt Island,Florida,USA,United States,170.0,66.0,NaN
77550,78141,Keith Brantly,1962-05-23,Scott Air Force Base,Illinois,USA,United States,180.0,64.0,NaN
84097,84766,Keith Christiansen,1944-07-14,International Falls,Minnesota,USA,United States,165.0,69.0,2018-11-05
94646,95413,Keith Meyer,1938-06-20,Geneva,Illinois,USA,United States,NaN,NaN,2010-07-25
97499,98286,Keith Tkachuk,1972-03-28,Melrose,Massachusetts,USA,United States,188.0,102.0,NaN
98068,98860,Keith Wegeman,1929-08-28,Denver,Colorado,USA,United States,NaN,NaN,1974-08-22
99921,100722,Keith Carney,1970-02-03,Providence,Rhode Island,USA,United States,188.0,93.0,NaN
115973,117348,Keith Sanderson,1975-02-02,Plymouth,Massachusetts,USA,United States,183.0,95.0,NaN

# Adding or removing columns

In [ ]:
coffee['price'] = 4.99
coffee.head()

         Day Coffee Type  Units Sold  price
0     Monday    Espresso          25   4.99
1     Monday       Latte          10   4.99
2    Tuesday    Espresso          10   4.99
3    Tuesday       Latte          10   4.99
4  Wednesday    Espresso          35   4.99

In [ ]:
import numpy as np

coffee['new_price']= np.where(coffee['Coffee Type']=='Espresso',3.99,5.99)
coffee.head()

         Day Coffee Type  Units Sold  price  new_price
0     Monday         100          25   4.99       5.99
1     Monday       Latte          10   4.99       5.99
2    Tuesday    Espresso          10   4.99       3.99
3    Tuesday       Latte          10   4.99       5.99
4  Wednesday    Espresso          35   4.99       3.99

In [ ]:
coffee.drop(columns = "price") #things get changed in the copy of df
coffee.drop(columns="price", inplace=True) #things get changed in the original df

In [ ]:
coffee.head()

         Day Coffee Type  Units Sold  new_price
0     Monday         100          25       5.99
1     Monday       Latte          10       5.99
2    Tuesday    Espresso          10       3.99
3    Tuesday       Latte          10       5.99
4  Wednesday    Espresso          35       3.99

In [ ]:
coffee['revenue'] = coffee['Units Sold'] * coffee['new_price']
coffee.head()

         Day Coffee Type  Units Sold  new_price  revenue
0     Monday         100          25       5.99   149.75
1     Monday       Latte          10       5.99    59.90
2    Tuesday    Espresso          10       3.99    39.90
3    Tuesday       Latte          10       5.99    59.90
4  Wednesday    Espresso          35       3.99   139.65

In [ ]:
coffee.rename(columns={'new_price':'price'},inplace=True)
coffee.head()

         Day Coffee Type  Units Sold  price  revenue
0     Monday         100          25   5.99   149.75
1     Monday       Latte          10   5.99    59.90
2    Tuesday    Espresso          10   3.99    39.90
3    Tuesday       Latte          10   5.99    59.90
4  Wednesday    Espresso          35   3.99   139.65

In [ ]:
bios_new = bios.copy()
bios_new['first_name'] = bios_new['name'].str.split().str[0]
bios_new.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Jean-François
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Arnaud
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Jean
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Jacques
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Albert

In [ ]:
bios_new['born_datetime'] = pd.to_datetime(bios_new['born_date'])
bios_new.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name,born_datetime
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Jean-François,1886-12-12
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Arnaud,1969-04-01
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Jean,1898-08-13
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Jacques,1895-05-11
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Albert,1878-04-17

In [ ]:
bios_new['born_year'] = bios_new['born_datetime'].dt.year
bios_new.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name,born_datetime,born_year
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Jean-François,1886-12-12,1886.0
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Arnaud,1969-04-01,1969.0
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Jean,1898-08-13,1898.0
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Jacques,1895-05-11,1895.0
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Albert,1878-04-17,1878.0

In [ ]:
# Saving our updated dataframe
bios_new.to_csv('bios_new.csv', index=False)

In [ ]:
# Using Lambda & Custom functions w/ .apply()

bios['height_category']=bios['height_cm'].apply(lambda x: 'Short' if x<160 else ('Average' if x<180 else 'Tall'))
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,height_category
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Tall
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Tall
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Tall
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Average
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Tall

In [ ]:
def categorize_athlete(row):
  if row['height_cm'] <170 and row['weight_kg'] < 70:
    return 'lightweight'
  elif row['height_cm'] <185 and row['weight_kg'] <= 80:
    return 'MiddleWeight'
  return 'heavyweight'

bios['Category']=bios.apply(categorize_athlete,axis=1)
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,height_category,Category
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Tall,heavyweight
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Tall,MiddleWeight
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Tall,MiddleWeight
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Average,lightweight
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Tall,heavyweight

# **Merging and concatenating data**

In [ ]:
nocs = pd.read_csv('noc_regions.csv')
nocs.head()

   NOC       region                 notes
0  AFG  Afghanistan                   NaN
1  AHO      Curacao  Netherlands Antilles
2  ALB      Albania                   NaN
3  ALG      Algeria                   NaN
4  AND      Andorra                   NaN

In [ ]:
bios_new_new =  pd.merge(bios,nocs, left_on='born_country', right_on='NOC', how='left')
bios_new_new.rename(columns={'region':'born_country_full'},inplace=True)
bios_new_new.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC_x,height_cm,weight_kg,died_date,height_category,Category,NOC_y,born_country_full,notes
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Tall,heavyweight,FRA,France,NaN
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Tall,MiddleWeight,FRA,France,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Tall,MiddleWeight,FRA,France,NaN
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Average,lightweight,FRA,France,NaN
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Tall,heavyweight,GBR,UK,NaN

In [ ]:
bios_new_new[bios_new_new['NOC_x'] != bios_new_new['born_country_full']][['name','NOC_x','born_country_full']]

                       name    NOC_x born_country_full
4              Albert Canet   France                UK
12                J. Defert   France               NaN
13           Étienne Durand   France               NaN
16               Guy Forget   France           Morocco
27       Guy, Baron Lejeune   France               NaN
...                     ...      ...               ...
145491        Matthew Wepke  Jamaica               NaN
145493   Landysh Falyakhova      ROC            Russia
145495    Polina Luchnikova      ROC            Russia
145496  Valeriya Merkusheva      ROC            Russia
145497      Yuliya Smirnova      ROC            Russia

[73210 rows x 3 columns]

In [ ]:
usa = bios[bios['born_country']=="USA"].copy()
gbr = bios[bios['born_country'] == "GBR"].copy()

In [ ]:
new_df = pd.concat([usa,gbr])

In [ ]:
new_df.tail()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,height_category,Category
144811,148512,Benjamin Alexander,1983-05-08,London,England,GBR,Jamaica,NaN,NaN,NaN,Tall,heavyweight
144815,148517,Ashley Watson,1993-10-28,Peterborough,England,GBR,Jamaica,NaN,NaN,NaN,Tall,heavyweight
145005,148716,Peder Kongshaug,2001-08-13,Wimbledon,England,GBR,Norway,184.0,86.0,NaN,Tall,heavyweight
145319,149041,Axel Brown,1992-04-02,Harrogate,England,GBR,Trinidad and Tobago,NaN,NaN,NaN,Tall,heavyweight
145388,149111,Jean-Luc Baker,1993-10-07,Burnley,England,GBR,United States,NaN,NaN,NaN,Tall,heavyweight

# **Handling Null values** (NaNs) | .fillna()  .interpolate() .dropna() .isna() .notna()

In [ ]:
coffee.loc[[3,5], 'Units Sold']=np.nan
coffee.isna().sum()

Day            0
Coffee Type    0
Units Sold     2
price          0
revenue        0
dtype: int64

In [ ]:
coffee['Units Sold'] = coffee['Units Sold'].interpolate()

In [ ]:

coffee

          Day Coffee Type  Units Sold  price  revenue
0      Monday         100      5000.0   5.99   149.75
1      Monday       Latte      5000.0   5.99    59.90
2     Tuesday    Espresso        10.0   3.99    39.90
3     Tuesday       Latte        22.5   5.99    59.90
4   Wednesday    Espresso        35.0   3.99   139.65
5   Wednesday       Latte        37.5   5.99   149.75
6    Thursday    Espresso        40.0   3.99   159.60
7    Thursday       Latte        30.0   5.99   179.70
8      Friday    Espresso        45.0   3.99   179.55
9      Friday       Latte        35.0   5.99   209.65
10   Saturday    Espresso        45.0   3.99   179.55
11   Saturday       Latte        35.0   5.99   209.65
12     Sunday    Espresso        45.0   3.99   179.55
13     Sunday       Latte        35.0   5.99   209.65

In [ ]:
# to drop all the Nas
coffee=coffee.dropna(subset=['Units Sold'], inplace=True)

# to check whether its na or not
coffee[coffee['Units Sold'].isna()]
coffee[coffee['Units Sold'].notna()]

# **Aggregating Data**

In [ ]:
bios['born_city'].value_counts()

born_city
Budapest           1378
Moskva (Moscow)     883
Oslo                708
Stockholm           629
Praha (Prague)      600
                   ...
Kirovgrad             1
Pereiaslav            1
Podgornyy             1
Kudepsta              1
Furmanov              1
Name: count, Length: 22368, dtype: int64

In [ ]:
bios[bios['born_country']=='USA']['born_region'].value_counts()

born_region
California              1634
New York                 990
Illinois                 585
Massachusetts            530
Pennsylvania             530
New Jersey               381
Texas                    368
Minnesota                365
Ohio                     328
Michigan                 319
Washington               240
Florida                  235
Wisconsin                209
Colorado                 207
Connecticut              156
Indiana                  150
Oregon                   132
Georgia                  129
Virginia                 121
Maryland                 117
District of Columbia     107
Iowa                     102
Hawaiʻi                   95
Kansas                    94
Oklahoma                  93
Louisiana                 92
Utah                      91
Missouri                  91
North Carolina            86
Arizona                   83
New Hampshire             83
Vermont                   68
Mississippi               66
Alabama                   64
Kentucky                  62
Tennessee                 62
Nebraska                  60
Rhode Island              56
Montana                   55
Maine                     50
South Carolina            50
Alaska                    45
Arkansas                  42
Idaho                     41
New Mexico                38
Nevada                    36
South Dakota              27
West Virginia             24
Delaware                  22
North Dakota              16
Wyoming                   14
Name: count, dtype: int64

In [ ]:
# Using Groupby- .groupby() .sum() .mean() .agg()
coffee.groupby(['Coffee Type'])['Units Sold'].sum()
coffee.groupby(['Coffee Type'])['Units Sold'].mean()

Coffee Type
100         5000.000000
Espresso      36.666667
Latte        742.142857
Name: Units Sold, dtype: float64

In [ ]:
coffee.groupby(['Coffee Type']).agg({'Units Sold': 'sum', 'price':'mean'})

             Units Sold  price
Coffee Type
100              5000.0   5.99
Espresso          220.0   3.99
Latte            5195.0   5.99

In [ ]:
# Pivot table
pivot = coffee.pivot(columns='Coffee Type',index='Day', values='revenue')
pivot

Coffee Type     100  Espresso   Latte
Day
Friday          NaN    179.55  209.65
Monday       149.75       NaN   59.90
Saturday        NaN    179.55  209.65
Sunday          NaN    179.55  209.65
Thursday        NaN    159.60  179.70
Tuesday         NaN     39.90   59.90
Wednesday       NaN    139.65  149.75

In [ ]:
pivot.loc['Monday','Latte']

np.float64(59.900000000000006)

In [ ]:
pivot.sum()

Coffee Type
100          149.75
Espresso     877.80
Latte       1078.20
dtype: float64

In [ ]:
# Group by combined with Datetime operations
bios['born_date'] = pd.to_datetime(bios['born_date'])
bios.groupby(bios['born_date'].dt.year)['name'].count()

born_date
1828.0      1
1831.0      2
1833.0      1
1836.0      1
1837.0      1
         ...
2005.0    163
2006.0     17
2007.0      3
2008.0      3
2009.0      1
Name: name, Length: 177, dtype: int64

# **Advanced Functionalities**

In [ ]:
coffee['yesterday_revenue']=coffee['revenue'].shift(1)
coffee

          Day Coffee Type  Units Sold  price  revenue  yesterday_revenue
0      Monday         100      5000.0   5.99   149.75                NaN
1      Monday       Latte      5000.0   5.99    59.90             149.75
2     Tuesday    Espresso        10.0   3.99    39.90              59.90
3     Tuesday       Latte        22.5   5.99    59.90              39.90
4   Wednesday    Espresso        35.0   3.99   139.65              59.90
5   Wednesday       Latte        37.5   5.99   149.75             139.65
6    Thursday    Espresso        40.0   3.99   159.60             149.75
7    Thursday       Latte        30.0   5.99   179.70             159.60
8      Friday    Espresso        45.0   3.99   179.55             179.70
9      Friday       Latte        35.0   5.99   209.65             179.55
10   Saturday    Espresso        45.0   3.99   179.55             209.65
11   Saturday       Latte        35.0   5.99   209.65             179.55
12     Sunday    Espresso        45.0   3.99   179.55             209.65
13     Sunday       Latte        35.0   5.99   209.65             179.55

In [ ]:
coffee['pct_change'] = coffee['revenue'] / coffee['yesterday_revenue']*100

In [ ]:
bios['height_rank']=bios['height_cm'].rank()

In [ ]:
bios.sort_values(['height_rank'],ascending=False)

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,height_category,Category,height_rank
28619,28832,Rosario Briones,1953-10-05,San Luis Potosí,San Luis Potosí,MEX,Mexico,127.0,42.0,NaN,Short,lightweight,106650.5
4515,4530,Lyton Mphande,1963-05-14,NaN,NaN,NaN,Malawi,127.0,62.0,NaN,Short,lightweight,106650.5
4516,4531,Helman Palije,1967-06-24,NaN,NaN,NaN,Malawi,128.0,74.0,NaN,Short,MiddleWeight,106649.0
4664,4681,Salvador Miranda,1949-09-13,NaN,NaN,NaN,Nicaragua,130.0,51.0,NaN,Short,lightweight,106647.5
4517,4532,Boston Simbeye,1959-12-24,NaN,NaN,NaN,Malawi,130.0,67.0,NaN,Short,lightweight,106647.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
145490,149217,Sin Ye-Chan,1995-06-13,NaN,NaN,NaN,Republic of Korea,NaN,NaN,NaN,Tall,heavyweight,NaN
145491,149218,Matthew Wepke,1989-12-05,NaN,NaN,NaN,Jamaica,NaN,NaN,NaN,Tall,heavyweight,NaN
145492,149219,Carlos García-Ordóñez,1927-04-24,La Habana (Havana),Ciudad de La Habana,CUB,Cuba,NaN,NaN,2019-11-24,Tall,heavyweight,NaN
145493,149220,Landysh Falyakhova,1998-08-31,Dva Polya Artash,Respublika Tatarstan,RUS,ROC,NaN,NaN,NaN,Tall,heavyweight,NaN
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20,Tall,heavyweight,NaN

In [ ]:
coffee.select_dtypes('float').cumsum().reset_index()

    index  Units Sold  price  revenue  yesterday_revenue   pct_change
0       0      5000.0   5.99   149.75                NaN          NaN
1       1     10000.0  11.98   209.65             149.75    40.000000
2       2     10010.0  15.97   249.55             209.65   106.611018
3       3     10032.5  21.96   309.45             249.55   256.736332
4       4     10067.5  25.95   449.10             309.45   489.874896
5       5     10105.0  31.94   598.85             449.10   597.107263
6       6     10145.0  35.93   758.45             598.85   703.684892
7       7     10175.0  41.92   938.15             758.45   816.278877
8       8     10220.0  45.91  1117.70             938.15   916.195404
9       9     10255.0  51.90  1327.35            1117.70  1032.959537
10     10     10300.0  55.89  1506.90            1327.35  1118.602275
11     11     10335.0  61.88  1716.55            1506.90  1235.366407
12     12     10380.0  65.87  1896.10            1716.55  1321.009145
13     13     10415.0  71.86  2105.75            1896.10  1437.773278

# **New Functionalities**

In [ ]:
results_numpy = pd.read_csv('results.csv')
results_arrow = pd.read_csv('results.csv',engine='pyarrow', dtype_backend='pyarrow')

In [ ]:
results_numpy.head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN

In [ ]:
results_numpy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 308408 entries, 0 to 308407
Data columns (total 11 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   year        305807 non-null  float64
 1   type        305807 non-null  object
 2   discipline  308407 non-null  object
 3   event       308408 non-null  object
 4   as          308408 non-null  object
 5   athlete_id  308408 non-null  int64
 6   noc         308407 non-null  object
 7   team        121714 non-null  object
 8   place       283193 non-null  float64
 9   tied        308408 non-null  bool
 10  medal       44139 non-null   object
dtypes: bool(1), float64(2), int64(1), object(7)
memory usage: 23.8+ MB

In [ ]:
results_arrow.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 308408 entries, 0 to 308407
Data columns (total 11 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   year        305807 non-null  double[pyarrow]
 1   type        305807 non-null  string[pyarrow]
 2   discipline  308407 non-null  string[pyarrow]
 3   event       308408 non-null  string[pyarrow]
 4   as          308408 non-null  string[pyarrow]
 5   athlete_id  308408 non-null  int64[pyarrow]
 6   noc         308407 non-null  string[pyarrow]
 7   team        121714 non-null  string[pyarrow]
 8   place       283193 non-null  double[pyarrow]
 9   tied        308408 non-null  bool[pyarrow]
 10  medal       44139 non-null   string[pyarrow]
dtypes: bool[pyarrow](1), double[pyarrow](2), int64[pyarrow](1), string[pyarrow](7)
memory usage: 37.5 MB

In [ ]:
results_numpy['as'].str.contains('Keith')

0         False
1         False
2         False
3         False
4         False
          ...
308403    False
308404    False
308405    False
308406    False
308407    False
Name: as, Length: 308408, dtype: bool

In [ ]:
# By: Aaditya Shirke